/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program;

/**
 *
 * @author diniristanti
 */
public class programku extends javax.swing.JFrame {

    public programku() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hari = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        guru1 = new javax.swing.JTextField();
        mapel1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        guru2 = new javax.swing.JTextField();
        mapel2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        guru3 = new javax.swing.JTextField();
        mapel3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        guru4 = new javax.swing.JTextField();
        mapel4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        guru5 = new javax.swing.JTextField();
        mapel5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        guru6 = new javax.swing.JTextField();
        mapel6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        guru7 = new javax.swing.JTextField();
        mapel7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        guru8 = new javax.swing.JTextField();
        mapel8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        guru9 = new javax.swing.JTextField();
        mapel9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        guru10 = new javax.swing.JTextField();
        mapel10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        guru11 = new javax.swing.JTextField();
        mapel11 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 15)); // NOI18N
        jLabel1.setText("Jadwal XI RPL 6");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 10, 120, 30);

        jLabel2.setText("Pilih Hari");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 60, 20);

        hari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Hari--", "Senin", "Selasa", "Rabu", "Kamis", "Jumat" }));
        hari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hariActionPerformed(evt);
            }
        });
        getContentPane().add(hari);
        hari.setBounds(110, 50, 120, 30);

        jLabel3.setText("1");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 130, 20, 14);

        guru1.setEditable(false);
        getContentPane().add(guru1);
        guru1.setBounds(380, 120, 190, 30);

        mapel1.setEditable(false);
        getContentPane().add(mapel1);
        mapel1.setBounds(120, 120, 210, 30);

        jLabel4.setText("2");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 170, 20, 14);

        guru2.setEditable(false);
        getContentPane().add(guru2);
        guru2.setBounds(380, 160, 190, 30);

        mapel2.setEditable(false);
        getContentPane().add(mapel2);
        mapel2.setBounds(120, 160, 210, 30);

        jLabel5.setText("3");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 210, 20, 14);

        guru3.setEditable(false);
        getContentPane().add(guru3);
        guru3.setBounds(380, 200, 190, 30);

        mapel3.setEditable(false);
        getContentPane().add(mapel3);
        mapel3.setBounds(120, 200, 210, 30);

        jLabel6.setText("4");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 250, 20, 14);

        guru4.setEditable(false);
        getContentPane().add(guru4);
        guru4.setBounds(380, 240, 190, 30);

        mapel4.setEditable(false);
        getContentPane().add(mapel4);
        mapel4.setBounds(120, 240, 210, 30);

        jLabel7.setText("5");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 290, 20, 14);

        guru5.setEditable(false);
        getContentPane().add(guru5);
        guru5.setBounds(380, 280, 190, 30);

        mapel5.setEditable(false);
        getContentPane().add(mapel5);
        mapel5.setBounds(120, 280, 210, 30);

        jLabel8.setText("6");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 330, 20, 14);

        guru6.setEditable(false);
        getContentPane().add(guru6);
        guru6.setBounds(380, 320, 190, 30);

        mapel6.setEditable(false);
        getContentPane().add(mapel6);
        mapel6.setBounds(120, 320, 210, 30);

        jLabel9.setText("7");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 370, 20, 14);

        guru7.setEditable(false);
        getContentPane().add(guru7);
        guru7.setBounds(380, 360, 190, 30);

        mapel7.setEditable(false);
        getContentPane().add(mapel7);
        mapel7.setBounds(120, 360, 210, 30);

        jLabel10.setText("8");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 410, 20, 14);

        guru8.setEditable(false);
        getContentPane().add(guru8);
        guru8.setBounds(380, 400, 190, 30);

        mapel8.setEditable(false);
        getContentPane().add(mapel8);
        mapel8.setBounds(120, 400, 210, 30);

        jLabel11.setText("9");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 450, 20, 14);

        guru9.setEditable(false);
        getContentPane().add(guru9);
        guru9.setBounds(380, 440, 190, 30);

        mapel9.setEditable(false);
        getContentPane().add(mapel9);
        mapel9.setBounds(120, 440, 210, 30);

        jLabel12.setText("10");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(60, 490, 20, 14);

        guru10.setEditable(false);
        getContentPane().add(guru10);
        guru10.setBounds(380, 480, 190, 30);

        mapel10.setEditable(false);
        getContentPane().add(mapel10);
        mapel10.setBounds(120, 480, 210, 30);

        jLabel13.setText("11");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(60, 530, 20, 14);

        guru11.setEditable(false);
        getContentPane().add(guru11);
        guru11.setBounds(380, 520, 190, 30);

        mapel11.setEditable(false);
        getContentPane().add(mapel11);
        mapel11.setBounds(120, 520, 210, 30);

        jLabel14.setText("Jam ke-");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(50, 90, 60, 14);

        jLabel15.setText("Mata Pelajaran");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(430, 90, 140, 20);

        jLabel16.setText("Guru");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(200, 90, 120, 20);

        setBounds(0, 0, 618, 612);
    }// </editor-fold>//GEN-END:initComponents

    private void hariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hariActionPerformed
        // TODO add your handling code here:
        if(hari.getSelectedItem().equals("Senin")){
            
            mapel1.setText("Upacara");
            guru1.setText("-");
            
            mapel2.setText("Pemrograman Desktop");
            guru2.setText("Hendro Soemarno, S.T.");           
            mapel3.setText("Pemrograman Desktop");
            guru3.setText("Hendro Soemarno, S.T.");
            
            mapel4.setText("Pendidikan Agama Islam");
            guru4.setText("Achmad Nasikin, M.Pd");            
            mapel5.setText("Pendidikan Agama Islam");
            guru5.setText("Achmad Nasikin, M.Pd");
            
            mapel6.setText("Pemrograman Web Dinamis");
            guru6.setText("Firdausa, S.Pd");           
            mapel7.setText("Pemrograman Web Dinamis");
            guru7.setText("Firdausa, S.Pd");
            mapel8.setText("Pemrograman Web Dinamis");
            guru8.setText("Firdausa, S.Pd");
            
            guru9.setText("Hirga Ertama Putra,S.Kom");
            mapel9.setText("Rancang Bangun Jaringan");
            guru10.setText("Hirga Ertama Putra,S.Kom");
            mapel10.setText("Rancang Bangun Jaringan");
            guru11.setText("Hirga Ertama Putra,S.Kom");
            mapel11.setText("Rancang Bangun Jaringan");
            
            
        }
        else
        if(hari.getSelectedItem().equals("Selasa")){
            mapel1.setText("Pemrograman Desktop");
            guru1.setText("Hendro Soemarno, S.T.");            
            mapel2.setText("Pemrograman Desktop");
            guru2.setText("Hendro Soemarno, S.T.");  
            
            mapel3.setText("Pendidikan Agama Islam");
            guru3.setText("Achmad Nasikin, M.Pd");
            
            mapel4.setText("Bahasa Jawa");
            guru4.setText("Sri Chusnul Haniyah,S.Pd");            
            mapel5.setText("Bahasa Jawa");
            guru5.setText("Sri Chusnul Haniyah,S.Pd");
            
            mapel6.setText("Matematika");
            guru6.setText("Tulus Andrianto,S.Pd");           
            mapel7.setText("Matematika");
            guru7.setText("Tulus Andrianto,S.Pd");
            mapel8.setText("Matematika");
            guru8.setText("Tulus Andrianto,S.Pd");
            
            guru9.setText("Susanto,S.Kom");
            mapel9.setText("Admin Server");
            guru10.setText("Susanto,S.Kom");
            mapel10.setText("Admin Server");
            guru11.setText("Susanto,S.Kom");
            mapel11.setText("Admin Server");
        }
        else
        if(hari.getSelectedItem().equals("Rabu")){
            mapel1.setText("Pemrograman Berorientasi Objek");
            guru1.setText("Muhamad Arifin");            
            mapel2.setText("Pemrograman Berorintasi Objek");
            guru2.setText("Muhamad Arifin");              
            mapel3.setText("Pemrograman Berorientasi Objek");
            guru3.setText("Muhamad Arifin");
            
            mapel4.setText("Sejarah Indonesia");
            guru4.setText("Andik Suharyanto,S.Pd");           
            mapel5.setText("Sejarah Indonesia");
            guru5.setText("Andik Suharyanto,S.Pd");
            
            mapel6.setText("Permodelan Perangkat Lunak");
            guru6.setText("Ifa Choirunnisa,S.T");
            mapel7.setText("Admin Server");
            guru7.setText("Ifa Choirunnisa,S.T");
                       
            guru8.setText("Firmansyah Ayatullah,S.Kom");
            mapel8.setText("Seni Budaya");
            guru9.setText("Firmansyah Ayatullah,S.Kom");
            mapel9.setText("Seni Budaya");
            
            guru10.setText("Larasati Khoirun Nisa, S.Pd");
            mapel10.setText("Bahasa Inggris");
            guru11.setText("Larasati Khoirun Nisa, S.Pd");
            mapel11.setText("Bahasa Inggris");
        }
        if(hari.getSelectedItem().equals("Kamis")){
            
            mapel1.setText("Basis Data");
            guru1.setText("Ifa Choirunnisa,S.T");            
            mapel2.setText("Basis Data");
            guru2.setText("Ifa Choirunnisa,S.T");           
            mapel3.setText("Basis Data");
            guru3.setText("Ifa Choirunnisa,S.T");
            
            mapel4.setText("Sistem Telekomunikasi");
            guru4.setText("Soelarso,S.T");            
            mapel5.setText("Sistem Telekomunikasi");
            guru5.setText("Soelarso,S.T");
            
            mapel6.setText("Bahasa Indonesia");
            guru6.setText("Felly Fitriani Supriyadi,S.S S.Pd");           
            mapel7.setText("Bahasa Indonesia");
            guru7.setText("Felly Fitriani Supriyadi,S.S S.Pd");
            mapel8.setText("Bahasa Indonesia");
            guru8.setText("Felly Fitriani Supriyadi,S.S S.Pd");
            
            mapel9.setText("BP/BK");
            guru9.setText("Dra. Peni Wardayani");
            
            mapel10.setText("Pendidikan Kewarganegaaan");
            guru10.setText("Fajar Setiyawan, S.Pd");
            mapel11.setText("Pendidikan Kewarganegaraan");
            guru11.setText("Fajar Setiyawan, S.Pd");
            
            
        }
        else
        if(hari.getSelectedItem().equals("Jumat")){
            mapel1.setText("Senam/Kajian/Jalan");
            guru1.setText("-");
            
            mapel2.setText("PKWU");
            guru2.setText("Titik Apriana Dewi,S.Pd");              
            mapel3.setText("PKWU");
            guru3.setText("Titik Apriana Dewi,S.Pd");
            
            mapel4.setText("Penjaskes");
            guru4.setText("Rofiqut Thoriq,S.Pd");            
            mapel5.setText("Penjaskes");
            guru5.setText("Rofiqut Thoriq,S.Pd");
            
            mapel6.setText("Fisika");
            guru6.setText("Drs. Ahmad Khuzaimi");           
            mapel7.setText("Fisika");
            guru7.setText("Drs. Ahmad Khuzaimi");
            
            mapel8.setText("Pemrograman Perangkat Bergerak");
            guru8.setText("Hendra Wahyu Prasetya,S.Kom");            
            guru9.setText("Hendra Wahyu Prasetya,S.Kom");
            mapel9.setText("Pemrograman Perangkat Bergerak");
            guru10.setText("Hendra Wahyu Prasetya,S.Kom");
            mapel10.setText("Pemrograman Perangkat Bergerak");
            guru11.setText("");
            mapel11.setText("");
        }
    }//GEN-LAST:event_hariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(programku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(programku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLmapel1(programku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(programku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new programku().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField guru1;
    private javax.swing.JTextField guru10;
    private javax.swing.JTextField guru11;
    private javax.swing.JTextField guru2;
    private javax.swing.JTextField guru3;
    private javax.swing.JTextField guru4;
    private javax.swing.JTextField guru5;
    private javax.swing.JTextField guru6;
    private javax.swing.JTextField guru7;
    private javax.swing.JTextField guru8;
    private javax.swing.JTextField guru9;
    private javax.swing.JComboBox<String> hari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mapel1;
    private javax.swing.JTextField mapel10;
    private javax.swing.JTextField mapel11;
    private javax.swing.JTextField mapel2;
    private javax.swing.JTextField mapel3;
    private javax.swing.JTextField mapel4;
    private javax.swing.JTextField mapel5;
    private javax.swing.JTextField mapel6;
    private javax.swing.JTextField mapel7;
    private javax.swing.JTextField mapel8;
    private javax.swing.JTextField mapel9;
    // End of variables declaration//GEN-END:variables
}
